notifications:
  slack: projetgo:jo0oI2zSh4vHUoJzBIgbWIAF#builds

language: node_js

node_js:
- '0.10'

before_install:
- npm -g install mocha

script:
- cd tests/
- mocha *

deploy:
  provider: heroku
  app: api-matching-swipe
  on: master
  strategy: git
  api_key:
    secure: lM1Ypcu1MGLXYMMyk0GnaOyIqjI68D62/8WK6Jwjz3rPSYe+86Xxz03rYVVP8g1aBqqWJ8i24iB2HG86boY2I5Z4zDPihHX3pmvXrErcXUbKMQN/QgzqcLd+kmNoAmvHVLyY+p5oKUuN++e37ekygG4qNYI5k+ewxZXg3pDAs9g=

branches:
  only:
  - master
